### ISSUE TITLE
Replace `println!` with `log` and Add logs for tests.

### ISSUE THREAD

**Issue by aneeshsharma** [Prototype-Aether/Aether-Lib#43]
Need to change `println!` messages to use [`log`](https://crates.io/crates/log) instead. 

Also need to add a logger for tests. [`test-log`](https://crates.io/crates/test-log) seems to be a good solution for this.

@HotMonkeyWings @Hu4k3n Do tell if you find other solutions for logging inside tests.

**Comment by Hu4k3n** [comment]
Log4j

**Comment by aneeshsharma** [comment]
@Hu4k3n https://docs.rs/log4rs/1.0.0/log4rs/
